# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

notificationsSections:
  - title: All
    filters: ""
  - title: Created
    filters: reason:author
  - title: Participating
    filters: reason:participating
  - title: Mentioned
    filters: reason:mention
  - title: Review Requested
    filters: reason:review-requested
  - title: Assigned
    filters: reason:assign
  - title: Subscribed
    filters: reason:subscribed
  - title: Team Mentioned
    filters: reason:team-mention

repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60

defaults:
  preview:
    open: true
    width: 0.45
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  notificationsLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30

keybindings: {}
repoPaths: {}

theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
  colors:
    text:
      primary: "#e0def4"
      secondary: "#908caa"
      inverted: "#191724"
      faint: "#6e6a86"
      warning: "#eb6f92"
      success: "#31748f"
    background:
      selected: "#2a283e"
    border:
      primary: "#403d52"
      secondary: "#524f67"
      faint: "#26233a"
    icon:
      newcontributor: "#f6c177"
      contributor: "#9ccfd8"
      collaborator: "#c4a7e7"
      member: "#ebbcba"
      owner: "#eb6f92"
      unknownrole: "#6e6a86"

pager:
  diff: ""

confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
includeReadNotifications: true
