#!/bin/sh
# See `zsh.nix`, but in short: `git` is wrapped such that calls to `git worktree` are
# intercepted and directed here, allowing for custom `git worktree root` and `git worktree checkout`
# commands to be used.

case $1 in
"worktree")
	case "$(git wt-root)" in
	*/.git)
		echo "error: not within a worktree-based repo"
		return 1
		;;
	*)
		return 0
		;;
	esac
	;;

root)
	git worktree || return 1
	cd "$(git wt-root)" || return 1
	;;

checkout)
	ROOT=$(git wt-root)

	shift
	git fetch

	if [ -d "$ROOT/$1" ]; then
		cd "$ROOT/$1" || return 1
	else
		(cd "$ROOT" && "$NIX_PROFILE/bin/git" worktree add "$@") || return 1
		if [ -d "$ROOT/$1" ]; then
			cd "$ROOT/$1" || return 1
		else
			echo "error: $1 is not a valid worktree"
			return 1
		fi
	fi
	;;

clone)
	shift
	git wt-clone "$@"
	;;

*)
	"$NIX_PROFILE/bin/git" worktree "$@"
	;;
esac
